apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: triton-inference-server
    release: {{ .Release.Name }}
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: grpc
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: metrics
  selector:
    app: triton-inference-server
    release: {{ .Release.Name }}
